name: Pomodoro
options:
  deploymentTarget:
    macOS: "14.0"
  bundleIdPrefix: com.local
settings:
  SWIFT_VERSION: "6"
  MACOSX_DEPLOYMENT_TARGET: "14.0"
targets:
  Pomodoro:
    type: application
    platform: macOS
    sources:
      - Pomodoro
    info:
      path: Info.plist
      properties:
        LSUIElement: true
        CFBundleIconFile: AppIcon
        CFBundleIconName: AppIcon
    settings:
      INFOPLIST_FILE: Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.local.pomodoro
      SWIFT_STRICT_CONCURRENCY: complete
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
